from typing import List

def show_move(move: List[int]) -> None: ...

class Gridentify:
    board: List[int] = ...
    score: int = ...
    @classmethod
    def __init__(cls, seed: int) -> None: ...
    def copy(self) -> Gridentify: ...
    def make_move(self, move: List[int]) -> None: ...
    def show_board(self) -> None: ...
    def valid_moves(self) -> List[List[int]]: ...

